SMODS.ConsumableType {
    key = "Lenormand",
    primary_colour = HEX("bdd5d2"),
    secondary_colour = HEX("bdd5d2"),
    collection_rows = { 6, 6 },
    shop_rate = 0.4,
    cards = {
        ["c_chm_anchor"] = true,
        ["c_chm_bear"] = true,
        ["c_chm_birds"] = true,
        ["c_chm_book"] = true,
        ["c_chm_child"] = true,
        ["c_chm_clover"] = true,
        ["c_chm_coffin"] = true,
        ["c_chm_cross"] = true,
        ["c_chm_crossroads"] = true,
        ["c_chm_dog"] = true,
        ["c_chm_fish"] = true,
        ["c_chm_flowers"] = true,
        ["c_chm_fox"] = true,
        ["c_chm_garden"] = true,
        ["c_chm_house"] = true,
        ["c_chm_key"] = true,
        ["c_chm_lady"] = true,
        ["c_chm_letter"] = true,
        ["c_chm_lily"] = true,
        ["c_chm_man"] = true,
        ["c_chm_mice"] = true,
        ["c_chm_moon"] = true,
        ["c_chm_mountain"] = true,
        ["c_chm_rider"] = true,
        ["c_chm_ring"] = true,
        ["c_chm_scythe"] = true,
        ["c_chm_ship"] = true,
        ["c_chm_snake"] = true,
        ["c_chm_stars"] = true,
        ["c_chm_stork"] = true,
        ["c_chm_sun"] = true,
        ["c_chm_tower"] = true,
        ["c_chm_tree"] = true,
        ["c_chm_whip"] = true
    },
    loc_txt = {
        name = "Lenormand",
        collection = "Lenormand Cards",
    }
}